services:
  mysql_db:  # Контейнер MySQL
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webservice  # Имя БД
#    ports:
#      - "3307:3306"  # Пробрасываем порт для подключения с хоста
    volumes:
      - mysql_data:/var/lib/mysql  # Сохраняем данные БД
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - common_net

  webservice:
    build: .  # Собираем из Dockerfile
    container_name: webservice
    ports:
      - "8080:8080"  # Пробрасываем порт приложения
    links:
      - "mysql_db:mysql"
    depends_on:
      mysql_db:
        condition: service_healthy  # Ждем, пока MySQL станет доступен
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/webservice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - ./logs:/app/logs
    networks:
      - common_net

networks:
  common_net:

volumes:
  mysql_data:  # Том для хранения данных MySQL