name: Deploy

on:
  push:
    branches: [main, master]

jobs:
  build-and-package:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.9.6

      - name: Build with Maven
        run: mvn clean package


      - name: Prepare Docker context
        run: |
          mkdir -p docker-context
          cp target/webservice.jar docker-context/webservice.jar
          cp Dockerfile docker-context/Dockerfile

      - name: Build Docker image
        run: |
          docker build -t my-webservice:${{ github.sha }} -t my-webservice:latest ./docker-context
      
      

      - name: Show image list
        run: docker images | findstr my-webservice
